ppEffectDestroy ppColor;
ppEffectDestroy ppBlur;
ppEffectDestroy ppInversion;
ppEffectDestroy ppGrain;
ppEffectDestroy nonapsi_ef;
ppEffectDestroy nonapsi_ef2;
deletevehicle snow;
deletevehicle ps;
ppEffectDestroy ppe;
ppEffectDestroy ppe2;
ppEffectDestroy ppe3;
ppEffectDestroy wetdist1;
setaperture 0;
"dynamicBlur" ppEffectAdjust [0];
"dynamicBlur" ppEffectCommit 16;